### ISSUE TITLE
Guide users to additional steps

### ISSUE THREAD

**Issue by andrewDoing** [microsoft/hydrate#2]
As a user I want guidance on the parts that were not automatically generated or some insight into what I might be missing to port over to fabrikate.

- [x] Determine what information to pre-populate in the yaml, for the additional services that were found in the cluster

- [x] Determine what information can be added as a comment in the generated yaml. 

- [x] Add more guidance to the yaml by using comments.

- [ ] Add information in the comments about the versions of the components so the user is aware of what version were pre-populated

#### Information that can be pre-populated
- Deployments that match existing Fabrikate components
- Deployments that don't match existing Fabrikate components
  - Name of the deployment

#### Information that the user must provide
- Deployments that don't match existing Fabrikate components
  - Source repository link
  - Path (if necessary)
  - Generator (if using Helm)
 
#### User Steps
1. Use hydrate to generate a component.yaml
2. No Match deployments need information to be added OR they must be commented out.
3. Follow the [Fabrikate Steps](https://github.com/Microsoft/fabrikate) to generate your manifests

**Comment by andrewDoing** [comment]
@andrebriggs @mtarng @madelineliao 
What I have currently is the following:

```yaml
# No Match Deployments
# In order to use these deployments with Fabrikate, follow the steps below.
# 1. Add the source (git repository link)
# 2. Add a path field (path within the git repository) ex: "path: stable/"
# 3. Specify helm for applications generated using a Helm chart ex: "type: helm"
# Otherwise, comment them out to prevent errors with Fabrikate generation.
# See here for Fabrikate steps: https://github.com/Microsoft/fabrikate
- name: spring-boot-api
  source: <source repository url>
  method: git
- name: spring-boot-ui 
  source: <source repository url>
  method: git
```
I think this should be sufficient information to help edit the generated component.yaml. What does everyone think?
